### ISSUE TITLE
Y1 driver dead :(

### ISSUE THREAD

**Issue by luckypants123** [Spark-Concepts/xPro-V5#106]
Went to run another test program to try and confirm [#98](https://github.com/Spark-Concepts/xPro-V5/issues/98) is solved for me.....aaaand the Y axis driver is dead/dying. 

Commanding it to do anything results in grinding noise as the motor pulses back and forth.

Swapped motors and confirmed its the Y1 driver.

It's brand new....think I've got about 4 hours of use out of this thing.

What's the warranty situation like? Can just the driver be replaced?

**Comment by toonaoki** [comment]
It's a similar symptom.
It's been less than a month since I got it, but the Y1's motor driver isn't working properly.
I noticed that the settings and motors are exactly the same as the X-axis, but vibrations occur and the Motor fault indicators are lit.
I would like to know the means to turn off the indicator.

I hope it can be replaced with just the motor driver ...
