### ISSUE TITLE
BM3D laser and spindle issue

### ISSUE THREAD

**Issue by byronendleton** [Spark-Concepts/xPro-V5#78]
Gday. i struggled to get the laser going but found the solution on here by updating to the correct firmware. it solved the laser issue but broke the spindle. when i switch back to spindle it turns slowly by itself and wont start when i hit the M4 comand. it does however spin when i hit the test fire laser button. laser is connected to the PWM output and spindle to the 0-10v. i swap plugs over when changing toolhead so they both go through the relay respectively. i have macros setup to change the frequency settings and laser enable etc. am i missing something?

**Comment by byronendleton** [comment]
any fixes yet? I'm getting 3v on the EN pin when in spindle mode and nothing selected to run. and the relay doesn't click anymore with the laser firmware. I've reverted back to the other firmware to use the spindle.

**Comment by minapieni** [comment]
I have issues too with XPro v5 and OPT laser with Lightburn. I can carve but laser won't stay off when moving between letters, curves etc. It will shut off when the carving is done but otherwise laser stays on when traveling. As far as I can understand, my settings are ok. I just don't get this. (My cheap 3018pro with laser  works just well with same settings in Lightburn). Any ideas how to fix this? Is Xpro GRBL in Lightburn settings?


![20220402_142754](https://user-images.githubusercontent.com/102864769/161386636-131ef999-07b4-4f26-9da9-e649ee5a68c0.jpg)

**Comment by Spark-Concepts** [comment]
Please try updating firmware to the latest release as of July 2022 - please repost if you are still having issues
